# -*- coding: utf-8 -*-
"""AI PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GcRjjyGUGjR9UrwAwjDdvd8YT5_ZxAhE

# AIR QUALITY PREDICTION USING REGRESSION

IMPORT LIBRARY
"""

# Step 1: Import library yang dibutuhkan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

"""PREPROCESSING DAN PENGOLAHAN AWAL DATA"""

# Step 2: Upload file AirQualityUCI.xlsx
uploaded = files.upload()

# Step 3: Load dataset dari file Excel
df = pd.read_excel("AirQualityUCI.xlsx")

# Step 4: Drop dua kolom terakhir yang kosong
df = df.iloc[:, :-2]

# Step 5: Ganti nilai -200 menjadi NaN (karena itu nilai error/missing)
df.replace(-200, np.nan, inplace=True)

# Step 6: Hapus baris yang mengandung nilai NaN
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

# Step 7: Ubah kolom Date menjadi format datetime
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y', errors='coerce')

# Step 8: Gabungkan kolom Date dan Time menjadi kolom DateTime
df['DateTime'] = pd.to_datetime(df['Date'].dt.strftime('%Y-%m-%d') + ' ' + df['Time'].astype(str), errors='coerce')

# Step 9: Atur DateTime sebagai indeks dan hapus kolom Date dan Time
df.set_index('DateTime', inplace=True)
df.drop(columns=['Date', 'Time'], inplace=True)

# Step 10: Tampilkan semua isi data
pd.set_option('display.max_rows', None)     # Tampilkan semua baris
pd.set_option('display.max_columns', None)  # Tampilkan semua kolom

# Step 11: Tampilkan seluruh isi data
df

"""PEMBAGIAN DATA (MANUAL DATA SPLITTING)"""

# Step 12: Tentukan rasio dan jumlah data untuk training dan testing
train_ratio = 0.8  # 80% training dan 20% testing
n_rows = len(df)
n_train = int(train_ratio * n_rows)

# Step 13: Acak data (shuffle) agar distribusi training/testing merata
df_shuffled = df.sample(frac=1, random_state=42).reset_index(drop=True)

# Step 14: Split data menjadi data training dan data testing
train_df = df_shuffled.iloc[:n_train]
test_df = df_shuffled.iloc[n_train:]

# Step 15: Tampilkan ukuran masing-masing set
print("Ukuran data train:", train_df.shape)
print("Ukuran data test :", test_df.shape)

"""PEMISAHAN FITUR DAN TARGET"""

# Step 16: Pisahkan fitur (X) dan target (y)
# Tentukan kolom target yang ingin diprediksi (CO(GT)
target_col = 'CO(GT)'

# Untuk data training
X_train = train_df.drop(columns=[target_col])
y_train = train_df[target_col]

# Untuk data testing
X_test = test_df.drop(columns=[target_col])
y_test = test_df[target_col]

# Step 17: Cek bentuk data hasil pemisahan fitur dan target
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape :", X_test.shape)
print("y_test shape :", y_test.shape)

"""VALIDASI JUMLAH DATA"""

# Step 18: Validasi jumlah data pada masing-masing subset
# Total data adalah gabungan dari X_train dan X_test
X = pd.concat([X_train, X_test])

# Cetak jumlah data
print(f"Total data : {len(X)}")
print(f"Data train : {len(X_train)}")
print(f"Data test  : {len(X_test)}")

"""NORMALISASI DATA"""

# Step 19: Hitung nilai rata-rata dan standar deviasi dari data training
X_mean = X_train.mean()
X_std = X_train.std()

# Step 20: Lakukan standarisasi pada data training dan data testing
X_train = (X_train - X_mean) / X_std
X_test = (X_test - X_mean) / X_std

"""IMPLEMENTASI REGRESI LINIER MANUAL"""

# Step 21: Konversi DataFrame ke NumPy array agar bisa dihitung secara numerik
X_train_np = X_train.to_numpy()
y_train_np = y_train.to_numpy()

X_test_np = X_test.to_numpy()
y_test_np = y_test.to_numpy()

# Step 22: Inisialisasi parameter awal
n_features = X_train_np.shape[1]
weights = np.zeros(n_features)  # bobot awal diset ke 0
bias = 0.0

# Step 23: Fungsi untuk melakukan prediksi
def predict(X, weights, bias):
    return np.dot(X, weights) + bias

# Step 24: Fungsi untuk menghitung Mean Squared Error (MSE)
def mse(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Step 25: Proses training dengan Gradient Descent
learning_rate = 0.001
epochs = 1000

for epoch in range(epochs):
    # Prediksi hasil
    y_pred = predict(X_train_np, weights, bias)

    # Hitung error
    error = y_train_np - y_pred

    # Update bobot dan bias dengan rumus turunan MSE (gradient descent)
    weights -= learning_rate * (-2 * np.dot(X_train_np.T, error) / len(X_train_np))
    bias -= learning_rate * (-2 * np.sum(error) / len(X_train_np))

    # Tampilkan loss setiap 100 epoch
    if epoch % 100 == 0:
        loss = mse(y_train_np, y_pred)
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

"""MENAMPILKAN NILAI ASLI (GROUND TRUTH)"""

# Step 26: Tampilkan nilai asli dari data testing
print("Nilai asli (ground truth) dari data testing:")
for i, actual in enumerate(y_test_np):
    print(f"Data ke-{i+1}: Asli = {actual:.2f}")

"""PREDIKSI DATA TESTING"""

# Step 27: Prediksi nilai target untuk data testing
y_pred = predict(X_test_np, weights, bias)

# Step 28: Tampilkan semua hasil prediksi
print("Hasil prediksi terhadap data testing:")
for i, pred in enumerate(y_pred):
    print(f"Data ke-{i+1}: Prediksi = {pred:.2f}")

"""PERBANDINGAN PREDIKSI DENGAN NILAI ASLI"""

# Step 29: Tampilkan perbandingan antara prediksi dan nilai asli
print("Perbandingan Prediksi vs Nilai Asli:")
for i, (actual, pred) in enumerate(zip(y_test_np, y_pred)):
    print(f"Data ke-{i+1}: Asli = {actual:.2f}, Prediksi = {pred:.2f}")

"""VISUALISASI GRAFIK NILAI ASLI, PREDIKSI, DAN PERBANDINGAN"""

plt.figure(figsize=(16,10))

# Step 30: Grafik Nilai Asli (y_test)
plt.subplot(3, 1, 1)
plt.plot(y_test_np, label='Nilai Asli', color='green', marker='o')
plt.title('Grafik Nilai Asli (y_test)')
plt.ylabel('Nilai')
plt.grid(True)
plt.legend()

# Step 31: Grafik Prediksi (y_pred)
plt.subplot(3, 1, 2)
plt.plot(y_pred, label='Prediksi', color='blue', marker='x')
plt.title('Grafik Prediksi (y_pred)')
plt.ylabel('Nilai')
plt.grid(True)
plt.legend()

# Step 32: Grafik Perbandingan Nilai Asli vs Prediksi
# Line Plot
plt.subplot(3, 1, 3)
plt.plot(y_test_np, label='Nilai Asli', color='green', marker='o')
plt.plot(y_pred, label='Prediksi', color='blue', marker='x')
plt.title('Perbandingan Nilai Asli vs Prediksi')
plt.ylabel('Nilai')
plt.grid(True)
plt.legend()

# Scatter Plot
plt.figure(figsize=(6,6))
plt.scatter(y_pred, y_test_np, color='blue', alpha=0.6, label="Prediksi")
plt.plot([y_pred.min(), y_pred.max()], [y_pred.min(), y_pred.max()],
color='red', linestyle='--', label="Ideal (y = y_pred)")
plt.title("Nilai Asli vs Prediksi")
plt.xlabel("Prediksi")
plt.ylabel("Nilai Asli")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

"""EVALUASI MODEL"""

# Step 33: MSE (Mean Squared Error)
mse_value = np.mean((y_test_np - y_pred) ** 2)

# Step 34: RMSE (Root Mean Squared Error)
rmse_value = np.sqrt(mse_value)

# Step 35: MAE (Mean Absolute Error)
mae_value = np.mean(np.abs(y_test_np - y_pred))

# Step 36: R² Score (Koefisien Determinasi)
ss_total = np.sum((y_test_np - np.mean(y_test_np)) ** 2)
ss_residual = np.sum((y_test_np - y_pred) ** 2)
r2_score = 1 - (ss_residual / ss_total)

# Step 37: Tampilkan hasil evaluasi
print("Hasil Evaluasi Model:")
print(f"MSE  : {mse_value:.4f}")
print(f"RMSE : {rmse_value:.4f}")
print(f"MAE  : {mae_value:.4f}")
print(f"R²   : {r2_score:.4f}")

"""VISUALISASI HASIL EVALUASI MODEL"""

# Step 38: Data evaluasi model
metrics = ['MSE', 'RMSE', 'MAE', 'R²']
values = [mse_value, rmse_value, mae_value, r2_score]

# Step 39: Membuat bar chart untuk hasil evaluasi model
plt.figure(figsize=(8, 5))
bars = plt.bar(metrics, values, color='skyblue', edgecolor='black')

# Step 40: Menambahkan label nilai di atas bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.02, f'{yval:.4f}', ha='center', va='bottom', fontsize=9)

# Step 41: Tambahkan judul dan label sumbu
plt.title('Hasil Evaluasi Model Regresi Linear')
plt.ylabel('Nilai Metrik')
plt.xlabel('Metrik Evaluasi')
plt.tight_layout()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""VALIDASI HASIL (K-FOLD CROSS VALIDATION)"""

# Step 42: Gabungkan kembali fitur dan label
X_all = X.to_numpy()
y_all = np.concatenate([y_train, y_test])

# Step 43: Tentukan jumlah fold
k = 5
fold_size = len(X_all) // k

mse_scores = []

# Step 44: Proses K-Fold Cross Validation
for i in range(k):
    # Tentukan indeks untuk fold ke-i
    start = i * fold_size
    end = (i + 1) * fold_size if i < k - 1 else len(X_all)

    X_val = X_all[start:end]
    y_val = y_all[start:end]

    X_train_fold = np.concatenate((X_all[:start], X_all[end:]), axis=0)
    y_train_fold = np.concatenate((y_all[:start], y_all[end:]), axis=0)

    # Inisialisasi bobot dan bias baru
    weights = np.zeros(X_train_fold.shape[1])
    bias = 0.0

    # Standardisasi data
    mean = np.mean(X_train_fold, axis=0)
    std = np.std(X_train_fold, axis=0)
    X_train_fold = (X_train_fold - mean) / std
    X_val = (X_val - mean) / std

    # Training model
    learning_rate = 0.001
    epochs = 500  # cukup 500 agar tidak terlalu lama

    for epoch in range(epochs):
        y_pred_fold = np.dot(X_train_fold, weights) + bias
        error = y_train_fold - y_pred_fold
        weights -= learning_rate * (-2 * np.dot(X_train_fold.T, error) / len(X_train_fold))
        bias -= learning_rate * (-2 * np.sum(error) / len(X_train_fold))

    # Evaluasi model
    y_val_pred = np.dot(X_val, weights) + bias
    mse = np.mean((y_val - y_val_pred) ** 2)
    mse_scores.append(mse)
    print(f"Fold {i+1}, MSE: {mse:.4f}")

# Step 45: Hitung rata-rata MSE
mean_mse = np.mean(mse_scores)
print(f"\nRata-rata MSE dari {k}-Fold: {mean_mse:.4f}")

"""VISUALISASI HASIL K-FOLD CROSS VALIDATION"""

# Step 46: Buat bar chart untuk MSE per fold
folds = ['Fold 1', 'Fold 2', 'Fold 3', 'Fold 4', 'Fold 5']
mse_values = mse_scores
plt.figure(figsize=(8, 5))
bars = plt.bar(folds, mse_values, color='skyblue', edgecolor='black')
plt.axhline(y=sum(mse_values)/len(mse_values), color='red', linestyle='--', label='Rata-rata MSE')
plt.ylim(0, max(mse_values) * 1.15)

# Step 47: Tambahkan label nilai di atas bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.02, f'{yval:.4f}', ha='center', va='bottom', fontsize=9)

# Step 48: Tampilkan hasil evaluasi
plt.title('Evaluasi MSE pada 5-Fold Cross Validation')
plt.ylabel('Mean Squared Error (MSE)')
plt.xlabel('Fold')
plt.legend()
plt.tight_layout()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()